version: '3'

services:
  nuxt-app:
    image: node:20.3.1
    working_dir: /app
    command: /bin/bash -c "npm i pnpm -g && pnpm install && pnpm build"
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongodb
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_DB_URI=mongodb://mongodb:27017/mydb

  redis:
    image: redis:latest
    ports:
      - '7379:6379'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
