version: '3'

services:
  redis:
    image: redis:latest
    volumes:
      - ${pwd}/data/redis:/data
      - ${pwd}/logs/redis:/usr/local/etc/redis
      - ${pwd}/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server --requirepass testpassWord --appendonly yes
    ports:
      - 6378:6379

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ${pwd}/data/mongo/data:/data/db
      - ${pwd}/conf/mongo.conf:/etc/mongo/mongo.conf
    command: mongod --config /etc/mongo/mongo.conf
    env_file: .env
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
